apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-service
  namespace: physics

spec:
  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: content-service

  template:
    metadata:
      labels:
        app: content-service

    spec:
      containers:
        - name: content-service
          image: ahmedrabie222000/physics-content-service:v10
          imagePullPolicy: Always

          ports:
            - containerPort: 3003

          env:
            - name: PORT
              value: "3003"

            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: physics-config
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: physics-config
                  key: DB_PORT

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: physics-secrets
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: physics-secrets
                  key: POSTGRES_PASSWORD

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: physics-secrets
                  key: POSTGRES_DB

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

          startupProbe:
            httpGet:
              path: /health
              port: 3003
            periodSeconds: 5
            failureThreshold: 30

          readinessProbe:
            httpGet:
              path: /health
              port: 3003
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 3003
            periodSeconds: 10

          securityContext:
            runAsNonRoot: true
            runAsUser: 100
            runAsGroup: 101
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
