apiVersion: v1
kind: Secret
metadata:
  name: physics-secrets
  namespace: physics
type: Opaque
stringData:
  JWT_SECRET: "physics-jwt-super-secret-2026"
  SESSION_SECRET: "physics-session-super-secret-2026"
 
  POSTGRES_USER: "physicsadmin"
  POSTGRES_PASSWORD: "physics-db-password-2026"
  POSTGRES_DB: "physics"
