apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: student-uploads-pvc
  namespace: physics

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: local-path

  resources:
    requests:
      storage: 2Gi
